-- ============================================================
-- Vexim Amazon Managed Operations — Supabase schema
-- ============================================================
-- Run this SQL in the Supabase SQL Editor after creating a new project.
-- Enable required extensions.
-- ============================================================

-- 1. Enable pgvector for similarity/ANN if you ever need it (optional)
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Profiles / RBAC
-- ------------------------------------------------------------
-- Store extended user info and role assignment.
-- Roles: 'admin', 'operator', 'viewer'
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  role TEXT NOT NULL DEFAULT 'viewer CHECK (role IN ('admin','operator','viewer'))),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Grant authenticated users ability to read their own profile
GRANT SELECT ON public.profiles TO authenticated;

-- 3. Amazon SKU inventory & metrics
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.amazon_skus (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  asin TEXT NOT NULL,
  sku TEXT,
  title TEXT NOT NULL,
  cogs NUMERIC(12,2) NOT NULL DEFAULT 0,
  current_price NUMERIC(12,2) NOT NULL DEFAULT 0,
  list_price NUMERIC(12,2),
  fee_per_unit NUMERIC(12,2) DEFAULT 0,
  referral_fee_pct NUMERIC(5,2) DEFAULT 15.00,
  -- Derived metrics
  contribution_profit NUMERIC(12,2) GENERATED ALWAYS AS (current_price - cogs - fee_per_unit) STORED,
  sales_last_30d INTEGER DEFAULT 0,
  avg_order_value NUMERIC(12,2),
  -- Risk & health fields
  margin_delta NUMERIC(8,2) DEFAULT 0,          -- change vs baseline
  inventory_qty INTEGER DEFAULT 0,
  reorder_point INTEGER DEFAULT 0,
  stockout_risk_score NUMERIC(5,2) DEFAULT 0,  -- 0-100
  price_volatility NUMERIC(5,2) DEFAULT 0,
  -- Timestamps
  last_ingested_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for common filters
CREATE INDEX IF NOT EXISTS idx_amazon_skus_asin ON public.amazon_skus(asin);
CREATE INDEX IF NOT EXISTS idx_amazon_skus_coogs ON public.amazon_skus(contribution_profit DESC);
CREATE INDEX IF NOT EXISTS idx_amazon_skus_stockout ON public.amazon_skus(stockout_risk_score DESC);

-- 4. Raw reviews ingested from SP-API or manual upload
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.raw_reviews (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  asin TEXT NOT NULL,
  reviewer_id TEXT,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title TEXT,
  body TEXT NOT NULL,
  verified_purchase BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now(),
  source TEXT DEFAULT 'sp_api' CHECK (source IN ('sp_api','manual','csv'))
);

-- Index for per-ASIN review queries
CREATE INDEX IF NOT EXISTS idx_raw_reviews_asin ON public.raw_reviews(asin, created_at DESC);

-- 5. Recommendations generated by the decision engine
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.recommendations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  asin TEXT NOT NULL,
  -- What kind of recommendation
  type TEXT NOT NULL CHECK (type IN ('price_adjust','replenish','review_response','inventory_transfer')),
  -- Proposed action
  proposed_value NUMERIC(12,2),       -- new price, qty, etc.
  -- Risk score computed by the system (0-100)
  risk_score NUMERIC(5,2) NOT NULL DEFAULT 0,
  -- Approval levels: L0 = auto, L1 = operator sign-off, L2 = admin sign-off
  required_approval_level TEXT NOT NULL DEFAULT 'L1' CHECK (required_approval_level IN ('L0','L1','L2')),
  -- Status flow: draft → pending_approval → approved → executed → rolled_back
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','pending_approval','approved','executed','rolled_back')),
  -- Audit fields
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  executed_at TIMESTAMPTZ,
  rollback_reason TEXT,
  -- Metadata
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_recommendations_asin ON public.recommendations(asin, status);
CREATE INDEX IF NOT EXISTS idx_recommendations_risk ON public.recommendations(risk_score DESC);

-- 6. Policy / exception queue
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.exceptions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  recommendation_id UUID REFERENCES public.recommendations(id) ON DELETE CASCADE,
  code TEXT NOT NULL,               -- e.g. 'P0','P1','P2','P3'
  message TEXT NOT NULL,
  resolved BOOLEAN DEFAULT FALSE,
  resolved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Index
CREATE INDEX IF NOT EXISTS idx_exceptions_resolved ON public.exceptions(resolved, created_at DESC);

-- ============================================================
-- Row Level Security (RLS) policies
-- ============================================================

-- -----------------------------------------------------------------
-- profiles: users can read all profiles (for role‑based UI) but only
--           update their own.  This is a simple policy; you can tighten
--           as needed.
-- -----------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "profiles_select_for_authenticated"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (true);   -- anyone logged in can read (role used for UI)

CREATE POLICY "profiles_upsert_own"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- -----------------------------------------------------------------
-- amazon_skus: authenticated users can read all SKUs; only users with
--              'admin' or 'operator' role can insert/update/delete.
-- -----------------------------------------------------------------
ALTER TABLE public.amazon_skus ENABLE ROW LEVEL SECURITY;

CREATE POLICY "skus_select_all"
  ON public.amazon_skus FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "skus_manage_operator"
  ON public.amazon_skus FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role IN ('admin','operator')
    )
  );

-- -----------------------------------------------------------------
-- raw_reviews: read‑only for everyone (authenticated); management via
--              admin only.
-- -----------------------------------------------------------------
ALTER TABLE public.raw_reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "reviews_select_all"
  ON public.raw_reviews FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "reviews_manage_admin"
  ON public.raw_reviews FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

-- -----------------------------------------------------------------
-- recommendations: 
--   • anyone can read (dashboard view)
--   • operator can create & update their own drafts
--   • admin can change status and approve
-- -----------------------------------------------------------------
ALTER TABLE public.recommendations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "recs_select_all"
  ON public.recommendations FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "recs_insert_operator"
  ON public.recommendations FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role IN ('admin','operator')
    )
  );

CREATE POLICY "recs_update_by_role"
  ON public.recommendations FOR UPDATE
  TO authenticated
  USING (
    -- operator may change status to 'approved' only if they are the assigned operator
    (required_approval_level = 'L1' AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'operator'))
    OR
    -- admin can change any field
    EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
  );

-- -----------------------------------------------------------------
-- exceptions: similar to recommendations
-- -----------------------------------------------------------------
ALTER TABLE public.exceptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "exceptions_select_all"
  ON public.exceptions FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "exceptions_manage_admin"
  ON public.exceptions FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );